<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Version>0.25.11</Version>
    <Authors>UvA-FNWI</Authors>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Connector for the Instructure Canvas REST API</Description>
    <PackageReleaseNotes>Fix assignment saving</PackageReleaseNotes>
	<PackageId>UvA.Connectors.Canvas</PackageId>
	<IsPackable>true</IsPackable>
	<RepositoryType>git</RepositoryType>
	<RepositoryUrl>https://github.com/UvA-FNWI/UvA.Connectors.Canvas</RepositoryUrl>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="StrawberryShake" Version="15.1.11" />
    <PackageReference Include="StrawberryShake.Core" Version="15.1.11" />
    <PackageReference Include="StrawberryShake.Transport.Http" Version="15.1.11" />
    <PackageReference Include="StrawberryShake.CodeGeneration.CSharp.Analyzers" Version="12.22.6" />
  </ItemGroup>

  <ItemGroup>
    <GraphQL Include="GraphQL\*.graphql" />
  </ItemGroup>

</Project>
