name: build and push to nuget

on:
  push:
    branches:
      - feature/DN-1666-IN-Create-pipelines-for-open-source-Nuget-packages

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.*

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Push
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'
    - run: dotnet nuget push "./bin/Release/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
